//We need to generate random numbers and problem. For example, when we are designing a game, we need to get some random numbers to provide some randomness to the users. We need to generate random numbers to generate this cases for testing problems and solutions. We need to generate random numbers in cryptography and many applications to generate these random numbers. We have library functions in almost all programming languages in the. random numbers generated by these library functions are generally pseudorandom. They are not to be random because they are generated by some fixed set of steps, right? You have some deterministic machine which is following some deterministic steps to generate the randomness. 1 such library function that generates super random function. and fun can be : 0 to RAND_MAX (randMax till 32767)
#include<iostream>
#include<cstdlib>
#include<ctime>
using namespace std;
int main(){
    for(int i=0;i<5;i++)
    cout<<rand()<<" ";//41 18467 6334 26500 19169     //it is bad way to use rand fun Because it prints same random numbers again and again.
    cout<<endl;
    cout<<endl;

    srand(time(NULL));
    for(int i=0;i<5;i++)
    cout<<rand()<<" ";//It generates different random numbers
    return 0;
}
